language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.4
  - DJANGO=1.5.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python runtests.py
branches:
  only:
    - develop
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-fluent"
    template:
      - "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
    skip_join: true
  email:
    recipients:
      - uruz@ur.uz
    on_success: never
    on_failure: always
